### ISSUE TITLE
app launch broken after running suggested gem pristine command on pentoo linux

### ISSUE THREAD

**Issue by sysfu** [ZeroChaos-/blue_hydra#11]
Launching blue_hydra 1.9.17 on latest version of pentoo flashes an error message about do_sqlite3 along with a suggestion to run the following command to fix it

`gem pristine do_sqlite3 --version 0.10.17`

Doing so breaks the application launch of blue_hydra with Invalid gemspec error in said do_sqlite3 library.

I'm new to gentoo/pentoo and not sure how to resolve this. Have tried running pentoo-updater and also reinstalling blue_hydra via emerge command but this did not fix.

**Comment by ZeroChaos-** [comment]
Yeah, ruby gave you bad advice.  Don't do that next time.  Reinstall the gem using emerge to unbreak it.

**Comment by sysfu** [comment]
> Yeah, ruby gave you bad advice. Don't do that next time. Reinstall the gem using emerge to unbreak it.

It is possible to modify blue_hydra to suppress the bad advice given by ruby during application launch? 

Otherwise future users could fall into the same trap.

**Comment by ZeroChaos-** [comment]
It sure isn't.  Those messages don't come from blue_hydra and cannot be suppressed afaik.  It's ruby whining about something and I am not even honestly sure what, since everything works fine.

**Comment by ZeroChaos-** [comment]
I fixed two of these in Pentoo, I'll see about the gentoo one https://github.com/pentoo/pentoo-overlay/commit/675142bb0ac1db3806bbeb42655908de3ec05b21
