### ISSUE TITLE
Can't run backup or make copy of /etc/blue_hydra.db while app is running

### ISSUE THREAD

**Issue by charliebabbitt1988** [ZeroChaos-/blue_hydra#15]
When running the blue_hydra application and using this shell command, it causes the blue_hydra app to prematurely exit with no visible errors.

```shell
timestamp=$(date +"%d-%m-%Y_%H:%M:%S")
/usr/bin/sqlite3 /etc/blue_hydra/blue_hydra.db -cmd ".backup '/etc/blue_hydra/blue_hydra_${timestamp}.db'"
```

This happens due to the OS file level lock that occurs with making a copy of the file.  The same effect can be achieved if running a "cp" shell command like this.

```shell
timestamp=$(date +"%d-%m-%Y_%H:%M:%S")
cp /etc/blue_hydra/blue_hydra.db /etc/blue_hydra/blue_hydra_${timestamp}.db
```

The other possible cause of this error is just trying to read any table in the /etc/blue_hydra.db file while the app is up and running.  Just trying to read table data can cause the application to exit prematurely.

I realize that this is a limitation of using SQLite.  The db file was not designed to be accessed by more than 1 OS process at a time.  If trying to make a copy or a backup of the /etc/blue_hydra.db file while the blue_hydra app is "live", then it causes the app to eventually exit with no visible errors.

Can any mods be made in ./lib/blue_hydra.rb in order to address this issue?

In the meantime, I can script a daemon/service to restart blue_hydra in the event that it shuts down from trying to do anything to the db file with any other OS process.

**Comment by charliebabbitt1988** [comment]
I may have found a very simple fix for this issue.  Initial testing with the following fix has gone well.  Make the bottom of ./lib/blue_hydra.rb look like this:

```ruby
# massive speed up of sqlite by using in memory journal, this results in an
  # increased potential of corrupted DBs so the above code is used to recover
  # from that.
  DataMapper.repository.adapter.select('PRAGMA synchronous = OFF')
  DataMapper.repository.adapter.select('PRAGMA journal_mode = MEMORY')
  DataMapper.repository.adapter.select('PRAGMA busy_timeout = 5000')
rescue => e
  BlueHydra.logger.error("#{e.class}: #{e.message}")
  log_message = ""
  e.backtrace.each do |line|
    BlueHydra.logger.error(line)
    log_message << line
  end
  BlueHydra::Pulse.send_event("blue_hydra", {
    key:       'blue_hydra_db_error',
    title:     'Blue Hydra Encountered DB Migration Error',
    message:   log_message,
    severity:  'FATAL'
  })
  exit 1
end

if BlueHydra::SyncVersion.count == 0
  BlueHydra::SyncVersion.new.save
end

BlueHydra::SYNC_VERSION = BlueHydra::SyncVersion.first.version
```
The simple addition of this line seems to mitigate the problem:
```ruby
  DataMapper.repository.adapter.select('PRAGMA busy_timeout = 5000')
```
An even higher value, like 10000 ms, or 10 seconds, wouldn't hurt for busy areas.

**Comment by ZeroChaos-** [comment]
No.  sqlite is not designed for multiple things to access it at the same time.  If you want to break it that's fine, you may keep the pieces.

I wrote a little wrapper forever ago which you may or may not find useful, but I'm not removing the lock as that increases the chances of database corruption.

https://github.com/pwnieexpress/pwn_pad_sources/blob/develop/scripts/blue_hydra.sh
