### ISSUE TITLE
Implement a way to exclude MACs and UUIDs

### ISSUE THREAD

**Issue by charliebabbitt1988** [ZeroChaos-/blue_hydra#2]
Please implement a way to exclude known MACs and UUIDs (e.g. devices owned by the user running blue hydra).

In the blue_hydra.yml file, something like:

exclude_macs
exclude_prox (or exclude_uuids)

Matching MACs or UUIDs wouldn't be written to the database.

Also, exclude options for the ui would be sweet. Something like:

ui_exc_filter_mac
ui_exc_filter_prox

Would this be a simple edit to blue_hydra/lib/blue_hydra/cli_user_interface.rb ?

Hail Blue Hydra!

**Comment by ZeroChaos-** [comment]
What is the use case here? It isn't hard, just curious.

**Comment by charliebabbitt1988** [comment]
The use case would be not recording data for the Bluetooth devices that you own and have already accounted for.

For example, I often have 2 Bluetooth dongles plugged into one system.  One Bluetooth dongle is for Bluetooth audio to a speaker (usually hci0) and the other is the configured interface for Blue Hydra (bt_device set to hci1).  Constantly recording data to the sqlite database and the log file (if enabled) from my own audio dongle isn't so desirable.

Theoretically, this should reduce the amount of data to the sqlite database and the log file (if rssi_log is set to true).  Space can be limited on a Raspberry Pi, for example.

Also, if you have a baseline of devices that are always around you, then you can exclude those also.  As an example, I might not care about my neighbors devices since they are always present.

This feature would be great for recording only devices that are foreign to your location.

Thank you for considering it.

*Edit*

Also, if a MAC or UUID has been excluded, then don't bother using l2ping for that device.  I forgot that part.

**Comment by ZeroChaos-** [comment]
please take a look at https://github.com/ZeroChaos-/blue_hydra/commit/bf1d68e53808dcfc69fb92766e07ee307d556223 and maybe test it out and let me know if you are happy with the implementation

**Comment by charliebabbitt1988** [comment]
Working well so far.  It seems to test good.

If you're good with it, then close this.

Thanks and good job.

Hail Blue Hydra.

**Comment by ZeroChaos-** [comment]
any further and I'd be making major breaking changes, so I'm good right here :-)
