### ISSUE TITLE
apt autoremove removes necessary ruby dependencies

### ISSUE THREAD

**Issue by charliebabbitt1988** [ZeroChaos-/blue_hydra#6]
After some system updates/upgrades in a Debian based distro, re-running "bundle install" is sometimes necessary in order to restore functionality to blue hyrda due to packages that were removed from the execution of "apt autoremove".

If possible, address this in an update so that using "apt autoremove" can be run without this consequence.

**Comment by ZeroChaos-** [comment]
the install instructions in the readme are the best I can do.  apt autoremove doesn't remove ruby gems installed by bundler, so I really have no idea what's wrong for you.  It seems more likely that you got a new version of ruby and needed to reinstall the needed gems.

**Comment by charliebabbitt1988** [comment]
There are 2 known workarounds for this issue:

1. If execution of ./bin/blue_hydra fails, then do the following:
   cd blue_hydra
   bundle install
   ./bin/blue_hydra

Or

2. cd blue_hydra
   bundle install
   bundle exec ./bin/blue_hydra

If trying to run Blue Hydra as a systemd service or as part of a script, then setting
BUNDLE_GEMFILE=${base_path}/blue_hydra/Gemfile
might also help.
